meta:
    extract_upstream: False

tasks:
  # - source: tasks.raw.get
  #   product: products/raw/get.csv

  - source: tasks.download.download_parquet
    name: download-dataset
    product: products/get/dataset.parquet
    params:
      uri: 'hf://datasets/data-is-better-together/fineweb-c/ita_Latn/train-00000-of-00001.parquet'

  - source: scripts/features/tf_idf_keywords.py
    name: tf_idf_keywords
    upstream: [download-dataset]
    product:
      nb: products/features/tf_idf_keywords.ipynb
      dataset: products/features/df_with_keywords.parquet 
    params:
      n_keywords: 5
  
  - source: tasks.haystack_pipelines.create_topic_extraction_pipeline
    name: create_llama_pipeline
    product: data/haystack_pipelines/llama_topic_extraction.yml
    params:
      model_id: "llama3.1:8b-instruct-q8_0"
      system_prompt_path: data/system_prompt.md
      ask_prompt_path: data/ask_prompt.md
      assistant_start: "<classe=\""
      stream_reaponse: False
  
  - source: tasks.haystack_pipelines.create_topic_extraction_pipeline
    name: create_deepseek_pipeline
    product: data/haystack_pipelines/deepseek_llama_topic_extraction.yml
    params:
      model_id: "deepseek-r1:8b-llama-distill-q8_0"
      system_prompt_path: data/system_prompt.md
      ask_prompt_path: data/ask_prompt.md
      assistant_start: "<classe=\""
      stream_reaponse: False
  
  - source: tasks.haystack_pipelines.create_topic_extraction_pipeline
    name: create_gemma_pipeline
    product: data/haystack_pipelines/gemma_topic_extraction.yml
    params:
      model_id: "gemma2:2b"
      system_prompt_path: data/system_prompt.md
      ask_prompt_path: data/ask_prompt.md
      assistant_start: "<classe=\""
      stream_reaponse: False

