tasks:
  - source: scripts/features/tf_idf_keywords.py
    name: tf_idf_keywords
    product:
      nb: products/features/tf_idf_keywords.ipynb
      dataset: products/features/df_with_keywords.parquet 
    params:
      n_keywords: 5
      source_dataset: 'hf://datasets/data-is-better-together/fineweb-c/ita_Latn/train-00000-of-00001.parquet'